import React from "react";
import { ApolloProvider } from "@apollo/client";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ApolloWrapper } from "./ApolloWrapper";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApolloWrapper>
      <AppRouterCacheProvider>
        <html lang="en">
          <body>{children}</body>
        </html>
      </AppRouterCacheProvider>
    </ApolloWrapper>
  );
}
